blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from myblog.sitemaps import PostSitemap


sitemaps = {
    "posts": PostSitemap,
}

urlpatterns = [
    path("admin/", admin.site.urls),
    path("blog/", include("myblog.urls", namespace="myblog")),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
]

blog/myblog/urls.py
from django.urls import path
from . import views
from .feed import LatestPostsFeed

app_name = "myblog"

urlpatterns = [
    # path('', views.PostListView.as_view(), name='post_list'),
    path("", views.post_list, name="post_list"),
    path("tag/<slug:tag_slug>/", views.post_list, name="post_list_by_tag"),
    path(
        "<int:year>/<int:month>/<int:day>/<slug:post>/",
        views.post_detail,
        name="post_detail",
    ),
    path("<int:post_id>/share/", views.post_share, name="post_share"),
    path("<int:post_id>/comment/", views.post_comment, name="post_comment"),
    path("feed/", LatestPostsFeed(), name="post_feed"),
    path("search/", views.post_search, name="post_search"),
]

blog/myblog/models.py
from django.db import models
from django.db.models.query import QuerySet
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager


class PublishedManager(models.Manager):
    def get_queryset(self) -> QuerySet:
        return super().get_queryset().filter(status=Post.Status.PUBLISHED)


class Post(models.Model):
    # Publication status
    class Status(models.TextChoices):
        DRAFT = "DF", "Draft"
        PUBLISHED = "PB", "Published"

    # Data fields
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="blog_posts"
    )

    title = models.CharField(max_length=250)
    slug = models.SlugField(max_length=250, unique_for_date="publish")
    body = models.TextField()

    publish = models.DateTimeField(default=timezone.now)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    status = models.CharField(
        max_length=2, choices=Status.choices, default=Status.DRAFT
    )

    # Managers
    objects = models.Manager()  # Default manager
    published = PublishedManager()  # Manager for published posts
    tags = TaggableManager()  # Manager for tags

    # Meta data
    class Meta:
        ordering = ["-publish"]
        indexes = [models.Index(fields=["-publish"])]

    def __str__(self) -> str:
        return self.title

    def _tags(self):
        return [t.name for t in self.tags.all()]

    def get_absolute_url(self) -> str:
        return reverse(
            "myblog:post_detail",
            args=[self.publish.year, self.publish.month, self.publish.day, self.slug],
        )


class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments")
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ["created"]
        indexes = [models.Index(fields=["created"])]

    def __str__(self) -> str:
        return f"Comment by {self.name} on {self.post}"

blog/myblog/forms.py
from django import forms
from .models import Comment


class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ["name", "email", "body"]


class SearchFForm(forms.Form):
    query = forms.CharField()

blog/myblog/views.py
from django.core.mail import send_mail
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse  # Http404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from django.db.models import Count
from django.contrib.postgres.search import (
    SearchVector,
    SearchQuery,
    SearchRank,
    # TrigramSimilarity,
)

# from django.views.generic import ListView

from taggit.models import Tag

from .models import Post
from .forms import EmailPostForm, CommentForm, SearchFForm


# View for processing a list of posts
def post_list(request: HttpRequest, tag_slug=None) -> HttpResponse:
    published_posts = Post.published.all()

    # Filtration by tag
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        published_posts = published_posts.filter(tags__in=[tag])

    # Pagination
    paginator = Paginator(published_posts, 4)
    page_number = request.GET.get("page", 1)

    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(
            paginator.num_pages
        )  # Return the last page if page index out of range
    except PageNotAnInteger:
        posts = paginator.page(1)  # Return the first page if page number not an integer

    return render(request, "myblog/post/list.html", {"posts": posts, "tag": tag})


# class PostListView(ListView):
#     queryset = Post.published.all()
#     context_object_name = "posts"
#     paginate_by = 5
#     template_name = "myblog/post/list.html"


# View for processing a single post page with comments
def post_detail(
    request: HttpRequest, year: int, month: int, day: int, post
) -> HttpResponse:
    """
    # Solution with try/except
    try:
        post = Post.published.get(publish__year=year, publish__month=month, publish__day=day, slug=post)
    except Post.DoesNotExist:
        raise Http404('Post not found')
    """

    # Solution with shortcut function (MVC)
    post = get_object_or_404(
        Post,
        status=Post.Status.PUBLISHED,
        slug=post,
        publish__year=year,
        publish__month=month,
        publish__day=day,
    )

    comments = post.comments.filter(active=True)
    form = CommentForm()

    # Finding similar posts by tags
    post_tags_ids = post.tags.values_list("id", flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count("tags")).order_by(
        "-same_tags", "-publish"
    )[:4]

    return render(
        request,
        "myblog/post/detail.html",
        {
            "post": post,
            "comments": comments,
            "form": form,
            "similar_posts": similar_posts,
        },
    )


# View for processing email form
def post_share(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, id=post_id)
    sent = False

    if request.method == "POST":
        form = EmailPostForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data  # cd - dictonary type {"form_field": data}
            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recomends you read {post.title}"
            message = (
                f"Read {post.title} at {post_url}\n\n"
                f"{cd['name']}'c comments: {cd['comments']}"
            )

            send_mail(subject, message, "anhimovn1@gmail.com", [cd["to"]])
            sent = True

    else:
        form = EmailPostForm()

    return render(
        request, "myblog/post/share.html", {"post": post, "form": form, "sent": sent}
    )


# View for processing comment form
@require_POST
def post_comment(request: HttpRequest, post_id: int) -> HttpResponse:
    post = get_object_or_404(Post, status=Post.Status.PUBLISHED, id=post_id)
    comment = None

    form = CommentForm(data=request.POST)
    if form.is_valid():
        comment = form.save(commit=False)  # Not save to db
        comment.post = post
        comment.save()

    return render(
        request,
        "myblog/post/comment.html",
        {"post": post, "form": form, "comment": comment},
    )


# View for search
def post_search(request: HttpRequest) -> HttpResponse:
    form = SearchFForm()
    query = None
    results = []

    if "query" in request.GET:
        form = SearchFForm(request.GET)

        # Simple search
        # if form.is_valid():
        #     query = form.cleaned_data["query"]
        #     results = Post.published.annotate(
        #         search=SearchVector("title", "body")
        #     ).filter(search=query)

        # Search with word stems highlighting and ranking results
        # if form.is_valid():
        #     query = form.cleaned_data["query"]
        #     search_vector = SearchVector("title", "body")  # config="any_language"
        #     search_query = SearchQuery(query)  # config="any_language"
        #     results = (
        #         Post.published.annotate(
        #             search=search_vector, rank=SearchRank(search_vector, search_query)
        #         )
        #         .filter(search=search_query)
        #         .order_by("-rank")
        #     )

        # Search with weighting requests
        if form.is_valid():
            query = form.cleaned_data["query"]
            search_vector = SearchVector("title", "A") \
                + SearchVector("body", "B") # Vectors with weights
            search_query = SearchQuery(query)
            results = (
                Post.published.annotate(
                    search=search_vector, rank=SearchRank(search_vector, search_query)
                )
                .filter(rank__gte=0.3)
                .order_by("-rank")
            )

        # Search with trigram similarity
        # if form.is_valid():
        #     query = form.cleaned_data["query"]
        #     results = (
        #         Post.published.annotate(
        #             similarity=TrigramSimilarity("title", query),
        #         )
        #         .filter(similarity__gt=0.1)
        #         .order_by("-similarity")
        #     )

    return render(
        request,
        "myblog/post/search.html",
        {"form": form, "query": query, "results": results},
    )

blog/myblog/templates/myblog/post/comment.html
{% extends "myblog/base.html" %}

{% block title %}Add a comment{% endblock title %}

{% block content %}
    {% if comment %}
        <h2>Your comment has been added.</h2>
        <p><a href="{{ post.get_absolute_url }}">Back to the post</a></p>
    {% else %}
        {% include "myblog/post/includes/comment_form.html" %}
    {% endif %}
{% endblock content %}

blog/myblog/templates/myblog/post/detail.html
{% extends 'myblog/base.html' %}
{% load blog_tags %}

{% block title %}{{ post.title }}{% endblock title %}

{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="date">
        Published {{ post.publish }} by {{ post.author.first_name }} {{ post.author.last_name }}
    </p>
    <a href="{% url "myblog:post_list" %}">Back to My Blog</a>
    {{ post.body|markdown }}

    <p class="tags">
        Tags:
        {% for tag in post.tags.all %}
            {{ tag.name }}
            {% if not forloop.last %}, {% endif %}
            {% empty %}
            No tags
        {% endfor %}
    </p>

    <p>
        <a href="{% url 'myblog:post_share' post.id %}">
            Share this post
        </a>
    </p>

    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
        {% empty %}
        There are no similar posts yet.
    {% endfor %}

    {% with comments.count as total_comments %}
        <h2>
            {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }} {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
    {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    {% include "myblog/post/includes/comment_form.html" %}
{% endblock content %}

blog/myblog/templates/myblog/post/latest_posts.html
<ul>
    {% for post in latest_posts %}
        <li>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </li>
    {% endfor %}
</ul>

blog/myblog/templates/myblog/post/list.html
{% extends 'myblog/base.html' %}
{% load blog_tags %}

{% block title %}My Blog{% endblock %}

{% block content %}
    <h1>My Blog</h1>
    {% if tag %}
        <h2>Posts tagged with "{{ tag.name }}"</h2>
    {% endif %}
    {% for post in posts %}
        <h2>
            <a href="{{ post.get_absolute_url }}">
                {{ post.title }}
            </a>
        </h2>

        <p class="tags">
            Tags:
            {% for tag in post.tags.all %}
                <a href="{% url "myblog:post_list_by_tag" tag.slug %}">
                    {{ tag.name }}
                </a>
                {% if not forloop.last %}, {% endif %}
                {% empty %}
                No tags
            {% endfor %}
        </p>

        <p class="date">
            Published {{ post.publish }} by {{ post.author.first_name }} {{ post.author.last_name }}
        </p>
        {{ post.body|truncatewords:30 }}
    {% endfor %}
    {% include "../pagination.html" with page=posts %}
{% endblock %}

blog/myblog/templates/myblog/post/search.html
{% extends "myblog/base.html" %}
{% load blog_tags %}

{% block title %}Search{% endblock title %}

{% block content %}
    {% if query %}
        <h1>Posts containing "{{ query }}"</h1>
        <h3>
            {% with results.count as total_results %}
                Found {{ total_results }} result{{ total_results|pluralize }}
            {% endwith %}
        </h3>

        {% for post in results %}
            <h3>
                <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
            </h3>
            {{ post.body|markdown|truncatewords_html:12 }}
        {% empty %}
            <p>There are no results for your query.</p>
        {% endfor %}
    {% else %}
        <h1>Search for posts</h1>
        <form method="get">
            {{ form.as_p }}
            <input type="submit" value="Search">
        </form>
    {% endif %}
{% endblock content %}

blog/myblog/templates/myblog/post/share.html
{% extends "myblog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form method="post">
            {{ form.as_p }}
            {% csrf_token %}
            <input type="submit" value="Send E-mail">
        </form>
    {% endif %}
{% endblock %}